name: Sync Fork

on:
  schedule:
    - cron: '0 22 * * *' # every day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: zwping/fork-sync@v1.6.5
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: yangzongzhuan
          base: master
          head: master
